In [2]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "mes": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"] * 2,
    "vendas": [120, 150, 170, 160, 200, 230, 100, 130, 160, 155, 190, 210],
    "produto": ["Produto A"] * 6 + ["Produto B"] * 6
})

df

    mes  vendas    produto
0   Jan     120  Produto A
1   Fev     150  Produto A
2   Mar     170  Produto A
3   Abr     160  Produto A
4   Mai     200  Produto A
5   Jun     230  Produto A
6   Jan     100  Produto B
7   Fev     130  Produto B
8   Mar     160  Produto B
9   Abr     155  Produto B
10  Mai     190  Produto B
11  Jun     210  Produto B

In [4]:
df = pd.DataFrame({
    "mes": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun"] * 2,
    "mes2": ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun"],
})

df

    mes mes2
0   Jan  Jan
1   Fev  Fev
2   Mar  Mar
3   Abr  Abr
4   Mai  Mai
5   Jun  Jun
6   Jan  Jan
7   Fev  Fev
8   Mar  Mar
9   Abr  Abr
10  Mai  Mai
11  Jun  Jun

In [3]:
df = pd.DataFrame({
    "horas_estudo": [1, 2, 3, 4, 5, 6, 7, 8],
    "nota": [8, 10, 11, 13, 14, 15, 17, 18],
    "turma": ["A", "A", "A", "B", "B", "B", "A", "B"]
})

df


df.dropna()

   horas_estudo  nota turma
0             1     8     A
1             2    10     A
2             3    11     A
3             4    13     B
4             5    14     B
5             6    15     B
6             7    17     A
7             8    18     B

In [11]:
lst1  = [1, 2, 3]
lst2 = ["A", "B", "C", "D", "E", "F", "G", "H"]


data = zip(lst1, lst2)


for v1, v2 in data:
    print(v1, v2)

1 A
2 B
3 C

ola "Gonçalo"

In [13]:
print("ola \\ \"Gonçalo\"")

ola \ "Gonçalo"

In [14]:
dados = pd.DataFrame(
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ],
    index=["Linha 1", "Linha 2", "Linha 3"],
    columns=["A", "B", "C"]
)

dados

          A   B   C
Linha 1  10  20  30
Linha 2  40  50  60
Linha 3  70  80  90

In [15]:
def foo(*args):
    print(args)

def boo(**kwargs):
    print(kwargs)

In [16]:
foo(1,2,12,31,12)

(1, 2, 12, 31, 12)

In [18]:
boo(v1=12, v2= 13, v3= 12)

{'v1': 12, 'v2': 13, 'v3': 12}